# This file describes the GitHub Actions workflow for continuous integration of XS Core.
name: XS Core CI

on:
  push:
    branches: [ master, ci-v2]
  pull_request:
    branches: [ master ]

jobs:
  build-emu:
    runs-on: self-hosted
    name: Make EMU
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          echo ::set-env name=AM_HOME::/home/ci-runner/xsenv/nexus-am
          echo ::set-env name=NEMU_HOME::/home/ci-runner/xsenv/NEMU
          echo ::set-env name=NOOP_HOME::$GITHUB_WORKSPACE
      - name: Build EMU
        run: make ./build/emu AM_HOME=$AM_HOME NEMU_HOME=$NEMU_HOME NOOP_HOME=$NOOP_HOME -j40