# This file describes the GitHub Actions workflow for continuous integration of XS Core.
name: XS Core CI

on:
  push:
    branches: [ master, ci-v2]
  pull_request:
    branches: [ master ]

jobs:
  build-emu:
    runs-on: self-hosted
    name: Make EMU
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          echo ::set-env name=AM_HOME::/home/ci-runner/xsenv/nexus-am
          echo ::set-env name=NEMU_HOME::/home/ci-runner/xsenv/NEMU
          echo ::set-env name=NOOP_HOME::$GITHUB_WORKSPACE
      - name: Build EMU
        run: make ./build/emu AM_HOME=$AM_HOME NEMU_HOME=$NEMU_HOME NOOP_HOME=$NOOP_HOME -j40

  cputest:
    runs-on: self-hosted
    name: Run cputest
    needs: [build-emu]
    steps:
      - name: Set env
        run: |
          echo ::set-env name=AM_HOME::/home/ci-runner/xsenv/nexus-am
          echo ::set-env name=NEMU_HOME::/home/ci-runner/xsenv/NEMU
          echo ::set-env name=NOOP_HOME::$GITHUB_WORKSPACE

      - name: Run cputest
        run: |
          echo $AM_HOME
          echo $NEMU_HOME
          echo $NOOP_HOME
          make -C $AM_HOME/tests/cputest/ ARCH=riscv64-noop V=OFF AM_HOME=$AM_HOME NEMU_HOME=$NEMU_HOME NOOP_HOME=$NOOP_HOME run -j20